### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by sockeqwe**
Hey @jshvarts

could you please take a look at the updated README? I have added a link to your repository.

Thanks again for sharing this!

### CODE REVIEW

**Comment by jshvarts** [comment]
IThanks Hannes! By the way, I recently added a Gradle sub-project to that repo https://github.com/jshvarts/MosbyMVP/tree/master/conductor-dagger-sample/ that has a multi-screen sample for Mosby and Conductor with Dagger. 

If you have comments about the Dagger portion or anything else, I would appreciate you opening an issue or creating a PR (there must be a better way to handle Presenter injection into View injections). 

Overall, Mosby makes MVP a lot better than so many custom implementations out there. Kudos to you!

**Comment by sockeqwe** [comment]
Thanks, I will take a look!
I think I have spotted an issue with ViewState in your sample repo. I will take a look soon and open an issue if it is really an issue.

**Comment by jshvarts** [comment]
Hey Hannes,

I've addressed one issue with ViewState in this sample. It's probably the one you've noticed before.

Commit: https://github.com/jshvarts/MosbyMVP/commit/6a8796f35e4c28c6aeb215e557e283faadb5239b

**Comment by sockeqwe** [comment]
Sorry, I haven_t had time lately to look into your code. But yes, this was the one I was referring to. I think there is one more thing, but I will open a dedicated issue for it in issue tracker on your repository

**Pull request merged**
